### ISSUE TITLE
--version is documented but is not implemented

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#179] opened 2018-09-27 22:03 UTC
```
: [ether@aquavit ~/bin]$; conch version
Conch Shell v1.6.1
  Git Revision: v1.6.1-0-ge46c5d6
  Build Time: 2018-09-14 09:54:11 -0700 PDT
  Build Host: buildbot@conch-buildbot
: [ether@aquavit ~/bin]$; 
: [ether@aquavit ~/bin]$; conch --version

Usage: conch [OPTIONS] COMMAND [arg...]

Command line interface for Conch
                           
Options:                   
      --version            Show the version and exit
...

```

**Comment by sungo** [comment] 2018-10-02 21:10
I hate to be the "works on my machine" person but 
```
$ bin/conch --version
1.6.1
```
and 
```
 ./conch-linux-amd64 --version                                                                                                                                                                                
1.6.1
```

**Comment by karenetheridge** [comment] 2018-10-02 21:28
Try this: `conch-darwin-amd64-v1.6.1 --profile <yourprofile> --version`. It fails as I describe.

**Comment by sungo** [comment] 2018-10-02 21:37
It looks to be a library issue that sadly probably won't get fixed until we switch to Cobra in #167. `--version` is handled by the tui library we're using and `--profile` is handled by our code. Putting `--profile` first on the command line triggers the library to run our code which errors out because no command was provided. `conch --version --profile <yourprofile>` works because the parser sees the `--version` and the library handles it on its own.

The extra fun part is that even if I declare a `--version` parameter, the same behavior occurs.

**Comment by karenetheridge** [comment] 2018-10-02 22:00
if it's just `--version` that's broken then I don't mind.  Would `--json` be a problem coming after `--profile` as well?

**Comment by sungo** [comment] 2018-10-02 22:03
In my local testing, that works fine. The issue is that the library is handling `--version`, not our code.

**Comment by sungo** [comment] 2018-12-05 15:34
This is fixed in conch v2

**Closed by sungo** 2018-12-05 15:34 UTC
